Repository bcgov/common-forms-toolkit, pull requests merged in 2020-05, with the labels that each got.

#4 Add basic knex/objection to code.
  app/config/default.json
  app/frontend/package.json
  app/knexfile.js
  app/package-lock.json
  app/package.json
  app/src/components/chesService.js
  app/src/components/clientConnection.js
  app/src/components/errorToProblem.js
  app/src/services/migrations/20200514082241_db-init.js
Labels: documentation, enhancement

#5 Add minimal stub PVC for potential file storage
  openshift/README.md
  openshift/app.dc.yaml
Labels: enhancement

#6 Feature/data model
  app/app.js
  app/knexfile.js
  app/package-lock.json
  app/package.json
  app/src/db/dataConnection.js
  app/src/db/migrations/20200514115312_001-forms.js
  app/src/db/migrations/20200514140356_002-minesattestations.js
  app/src/db/migrations/20200515095252_003-minesattestations-submission.js
  app/src/db/migrations/20200515134601_004-minesattestations-seed-data.js
  app/src/db/models/mixins.js
  app/src/forms/form/constants.js
  app/src/forms/form/controller.js
  app/src/forms/form/dataService.js
  app/src/forms/form/index.js
  app/src/forms/form/models/base.js
  app/src/forms/form/models/index.js
  app/src/forms/form/routes.js
  app/src/forms/minesattestations/constants.js
  app/src/forms/minesattestations/controller.js
  app/src/forms/minesattestations/dataService.js
  app/src/forms/minesattestations/index.js
  app/src/forms/minesattestations/models/base.js
  app/src/forms/minesattestations/models/index.js
  app/src/forms/minesattestations/models/submission.js
  app/src/forms/minesattestations/routes.js
  app/src/routes/v1.js
  app/src/services/migrations/20200514082241_db-init.js
  app/tests/unit/routes/v1.spec.js
Labels: enhancement

#9 Implement hasLogin meta route functionality - hide by default
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/src/router/index.js
  app/frontend/tests/unit/components/base/BaseAuthButton.spec.js
Labels: enhancement

#8 Initial UI copy
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/base/BaseContactCard.vue
  app/frontend/src/components/base/BaseInfoCard.vue
  app/frontend/src/components/base/BaseWarningCard.vue
  app/frontend/src/components/common/CityLookup.vue
  app/frontend/src/components/common/GeneratePdfButton.vue
  app/frontend/src/components/common/OrgBookSearch.vue
  app/frontend/src/components/minesattestations/Form.vue
  app/frontend/src/components/minesattestations/RequestReceipt.vue
  app/frontend/src/components/minesattestations/Step1.vue
  app/frontend/src/components/minesattestations/Step2.vue
  app/frontend/src/components/minesattestations/Step3.vue
  app/frontend/src/components/minesattestations/Step4.vue
  app/frontend/src/components/minesattestations/Step5.vue
  app/frontend/src/components/minesattestations/Step6.vue
  app/frontend/src/services/emailService.js
  app/frontend/src/services/minesAttestations/minesAttestationsService.js
  app/frontend/src/store/modules/minesAttestations/minesAttestationsForm.js
  app/frontend/src/views/minesattestations/Root.vue
  app/frontend/tests/unit/views/minesattestations/Root.spec.js
Labels: enhancement

#10 Feature/basic admin api
  app/src/db/migrations/20200514140356_002-minesattestations.js
  app/src/db/migrations/20200515134601_004-minesattestations-seed-data.js
  app/src/forms/minesattestations/controller.js
  app/src/forms/minesattestations/dataService.js
  app/src/forms/minesattestations/models/base.js
  app/src/forms/minesattestations/models/submission.js
  app/src/forms/minesattestations/routes.js
Labels: enhancement

#11 FE form
  app/frontend/src/components/minesattestations/Step2.vue
  app/frontend/src/components/minesattestations/Step3.vue
  app/frontend/src/components/minesattestations/Step4.vue
  app/frontend/src/components/minesattestations/Step5.vue
  app/frontend/src/components/minesattestations/Step6.vue
  app/frontend/src/services/minesAttestations/minesAttestationsService.js
  app/frontend/src/store/index.js
  app/frontend/src/store/modules/minesAttestations/minesAttestationsForm.js
  app/frontend/src/store/modules/minesAttestations/sampleData.js
  app/frontend/src/utils/constants.js
Labels: enhancement

#13 Post form to API
  app/config/default.json
  app/frontend/src/components/minesattestations/Step3.vue
  app/frontend/src/components/minesattestations/Step6.vue
  app/frontend/src/store/modules/minesAttestations/minesAttestationsForm.js
Labels: enhancement

#15 Submissions Query Results... but smaller
  app/src/forms/minesattestations/dataService.js
  app/src/forms/minesattestations/middleware/searchParameters.js
  app/src/forms/minesattestations/models/searchParameters.js
  app/src/forms/minesattestations/models/submission.js
Labels: enhancement

#17 Add Status Code API
  app/knexfile.js
  app/package-lock.json
  app/package.json
  app/src/db/models/mixins.js
  app/src/forms/form/models/base.js
  app/src/forms/minesattestations/controller.js
  app/src/forms/minesattestations/dataService.js
  app/src/forms/minesattestations/middleware/auth.js
  app/src/forms/minesattestations/middleware/index.js
  app/src/forms/minesattestations/models/base.js
  app/src/forms/minesattestations/models/submission.js
  app/src/forms/minesattestations/routes.js
Labels: enhancement

#21 Fix BCGov Logo being sized incorrectly on Edge Browser
  app/frontend/src/components/bcgov/BCGovHeader.vue
Labels: bug

#20 Update Submission & Common-ize some code.
  app/knexfile.js
  app/package.json
  app/src/db/dataConnection.js
  app/src/db/migrations/20200515095252_003-minesattestations-submission.js
  app/src/forms/common/middleware/auth.js
  app/src/forms/common/middleware/dataErrors.js
  app/src/forms/common/middleware/index.js
  app/src/forms/common/models/index.js
  app/src/forms/common/models/jsonSchema.js
  app/src/forms/common/models/mixins.js
  app/src/forms/form/middleware/index.js
  app/src/forms/form/models/base.js
  app/src/forms/minesattestations/constants.js
  app/src/forms/minesattestations/dataService.js
  app/src/forms/minesattestations/middleware/auth.js
  app/src/forms/minesattestations/middleware/checkRole.js
  app/src/forms/minesattestations/middleware/dataErrors.js
  app/src/forms/minesattestations/middleware/index.js
  app/src/forms/minesattestations/models/base.js
  app/src/forms/minesattestations/models/submission.js
  app/src/forms/minesattestations/routes.js
  app/tests/postman/COMFORT_API.postman_collection.json
  app/tests/postman/COMFORT_API_v1.postman_collection.json
Labels: enhancement

#24 Update datamodel - many-to-many version and status codes
  app/src/db/migrations/20200514140356_002-minesattestations.js
  app/src/db/migrations/20200515134601_004-minesattestations-seed-data.js
  app/src/forms/minesattestations/controller.js
  app/src/forms/minesattestations/dataService.js
  app/src/forms/minesattestations/models/base.js
  app/src/forms/minesattestations/routes.js
Labels: enhancement

#25 Change favicon from vuetify to bcgov logo
  app/frontend/public/favicon.ico
Labels: enhancement

#26 Add transportation fields to attestation
  app/src/db/migrations/20200519130421_005-minesattestations-transpo.js
  app/src/forms/minesattestations/models/submission.js
Labels: enhancement

#27 New transportation fields
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/minesattestations/Form.vue
  app/frontend/src/components/minesattestations/Step3.vue
  app/frontend/src/components/minesattestations/Step6.vue
  app/frontend/src/components/minesattestations/admin/AdminReviewSubmission.vue
  app/frontend/src/store/modules/minesAttestations/minesAttestationsForm.js
Labels: enhancement

#28 Various frontend bugfixes
  app/config/default.json
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/components/common/Dashboard.vue
  app/frontend/src/components/minesattestations/admin/AdminNavBar.vue
  app/frontend/src/router/index.js
  app/frontend/src/utils/constants.js
  app/frontend/src/views/Home.vue
  app/frontend/src/views/MinesAttestations.vue
  app/frontend/src/views/minesattestations/Admin.vue
  app/frontend/src/views/minesattestations/InspectionDashboard.vue
  app/frontend/src/views/minesattestations/PublicDashboard.vue
  app/frontend/src/views/minesattestations/Root.vue
  app/frontend/src/views/minesattestations/Submission.vue
  app/frontend/tests/unit/components/base/BaseAuthButton.spec.js
  app/frontend/tests/unit/store/modules/auth.getters.spec.js
  app/frontend/tests/unit/views/Home.spec.js
Labels: bug, enhancement

#29 Update all BaseSecure page permissions
  app/config/default.json
  app/frontend/src/views/minesattestations/Admin.vue
  app/frontend/src/views/minesattestations/InspectionDashboard.vue
  app/frontend/src/views/minesattestations/PublicDashboard.vue
  app/frontend/src/views/minesattestations/Submission.vue
  app/frontend/tests/unit/App.spec.js
Labels: bug, enhancement

#31 Convert form store module to be lazy-loaded
  app/frontend/src/store/index.js
  app/frontend/src/views/MinesAttestations.vue
  app/frontend/tests/unit/views/MinesAttestations.spec.js
Labels: enhancement

#34 BUG - migration down error on status code/version status code
  app/src/db/migrations/20200514140356_002-minesattestations.js
  app/src/forms/minesattestations/emailService.js
Labels: bug

#35 Drop @vue/cli-plugin-e2e-cypress
  app/frontend/cypress.json
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/tests/e2e/.eslintrc.js
  app/frontend/tests/e2e/plugins/index.js
  app/frontend/tests/e2e/specs/App.spec.js
  app/frontend/tests/e2e/support/commands.js
  app/frontend/tests/e2e/support/index.js
Labels: enhancement

#36 actionDate added to Submission Status.
  app/src/db/migrations/20200520101240_007-status-action-date.js
  app/src/forms/minesattestations/models/submission.js
Labels: enhancement

#38 Prevent page refresh on email enter
  app/frontend/src/components/minesattestations/RequestReceipt.vue
  app/frontend/src/components/minesattestations/Step6.vue
Labels: bug

#41 Feature/cdogs
  app/package-lock.json
  app/package.json
  app/src/components/cdogsService.js
  app/src/components/chesService.js
  app/src/db/migrations/20200520150352_008-submission-pdf-settings.js
  app/src/forms/minesattestations/assets/generate-submission-pdf.docx
  app/src/forms/minesattestations/assets/generate-submission-pdf.json
  app/src/forms/minesattestations/assets/index.js
  app/src/forms/minesattestations/controller.js
  app/src/forms/minesattestations/pdfService.js
  app/src/forms/minesattestations/routes.js
Labels: enhancement

#40 Update GeneratePDFButton to be contextually aware of current form route
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/components/common/GeneratePdfButton.vue
  app/frontend/src/components/minesattestations/Step6.vue
  app/frontend/src/components/minesattestations/admin/SubmissionsTable.vue
  app/frontend/src/services/helloService.js
  app/frontend/src/services/index.js
  app/frontend/src/views/NotFound.vue
Labels: bug, enhancement

#45 Rename Backend to minesoperatorscreening.
  .gitignore
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/minesattestations/admin/inspection/InspectionPanel.vue
  app/frontend/src/components/minesattestations/admin/inspection/NotesPanel.vue
  app/frontend/src/services/minesAttestations/minesAttestationsService.js
  app/frontend/src/utils/constants.js
  app/frontend/src/views/minesattestations/Admin.vue
  app/frontend/src/views/minesattestations/InspectionDashboard.vue
  app/frontend/src/views/minesattestations/PublicDashboard.vue
  app/frontend/src/views/minesattestations/Submission.vue
  app/package.json
  app/src/db/migrations/20200514140356_002-minesoperatorscreening.js
  app/src/db/migrations/20200515095252_003-minesoperatorscreening-submission.js
  app/src/db/migrations/20200515134601_004-minesoperatorscreening-seed-data.js
  app/src/db/migrations/20200519140119_005-settings-table.js
  app/src/db/migrations/20200519164226_006-settings-table-data.js
  app/src/db/migrations/20200520101240_007-status-action-date.js
  app/src/db/migrations/20200520150352_008-submission-pdf-settings.js
  app/src/forms/minesoperatorscreening/assets/confirmation-number-email.html
  app/src/forms/minesoperatorscreening/assets/generate-submission-pdf-001.docx
  app/src/forms/minesoperatorscreening/assets/generate-submission-pdf-001.html
  app/src/forms/minesoperatorscreening/assets/generate-submission-pdf-001.json
  app/src/forms/minesoperatorscreening/assets/status-assignment-email.html
  app/src/forms/minesoperatorscreening/constants.js
  app/src/forms/minesoperatorscreening/controller.js
  app/src/forms/minesoperatorscreening/dataService.js
  app/src/forms/minesoperatorscreening/emailService.js
  app/src/forms/minesoperatorscreening/index.js
  app/src/forms/minesoperatorscreening/middleware/checkRole.js
  app/src/forms/minesoperatorscreening/middleware/index.js
  app/src/forms/minesoperatorscreening/middleware/searchParameters.js
  app/src/forms/minesoperatorscreening/models/base.js
  app/src/forms/minesoperatorscreening/models/index.js
  app/src/forms/minesoperatorscreening/models/searchParameters.js
  app/src/forms/minesoperatorscreening/models/submission.js
  app/src/forms/minesoperatorscreening/pdfService.js
  app/src/forms/minesoperatorscreening/routes.js
  app/src/routes/v1.js
  app/tests/postman/MinesOperatorScreening_v1.postman_collection.json
Labels: enhancement

#47 SHOWCASE-1146
  app/src/db/migrations/20200521134300_007-settings-receipt-to-submission.js
  app/src/forms/minesoperatorscreening/controller.js
  app/src/forms/minesoperatorscreening/dataService.js
  app/src/forms/minesoperatorscreening/routes.js
  app/tests/postman/MinesOperatorScreening_v1.postman_collection.json
Labels: enhancement

#49 Add Caddy based reverse-proxy deploymentconfig
  openshift/README.md
  openshift/caddy-reverse-proxy.dc.yaml
Labels: enhancement

#51 Fix missed rename in default.json
  app/config/default.json
Labels: bug

#52 Initial POC of settings page
  app/frontend/src/components/minesoperatorscreening/admin/settings/SettingItem.vue
  app/frontend/src/components/minesoperatorscreening/admin/settings/SettingsPanel.vue
  app/frontend/src/router/index.js
  app/frontend/src/services/minesOperatorScreeningService.js
  app/frontend/src/views/minesoperatorscreening/Settings.vue
  app/src/forms/minesoperatorscreening/routes.js
Labels: enhancement

#54 Add permission check visibility on certain buttons
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/FormList.vue
  app/frontend/src/components/minesoperatorscreening/admin/AdminNavBar.vue
  app/frontend/src/utils/constants.js
  app/package-lock.json
  app/package.json
Labels: enhancement

#56 Frontend Dashboard Refactor
  app/config/custom-environment-variables.json
  app/config/default.json
  app/frontend/src/components/common/Dashboard.vue
  app/frontend/src/components/minesoperatorscreening/admin/AdminNavBar.vue
  app/frontend/src/router/index.js
  app/frontend/src/services/minesOperatorScreeningService.js
  app/frontend/src/views/minesoperatorscreening/Dashboards.vue
  app/frontend/src/views/minesoperatorscreening/InspectionDashboard.vue
  app/frontend/src/views/minesoperatorscreening/PublicDashboard.vue
  openshift/README.md
Labels: enhancement

#58 Show Test Data Button when not in PROD.
  app/frontend/src/components/minesoperatorscreening/Step2.vue
Labels: enhancement

#60 Feature/public rate limiter
  app/config/default.json
  app/package-lock.json
  app/package.json
  app/src/forms/common/middleware/index.js
  app/src/forms/common/middleware/rateLimiter.js
  app/src/forms/form/routes.js
  app/src/forms/minesoperatorscreening/routes.js
Labels: enhancement

#65 Change dashboard contents to be full-width page
  app/frontend/src/views/minesoperatorscreening/Dashboards.vue
Labels: bug

#67 Enable SonarQube Reporting
  Jenkinsfile.cicd
  README.md
  app/frontend/jest.config.js
  app/jest.config.js
  openshift/commonPipeline.groovy
Labels: enhancement

#68 User Management
  app/config/custom-environment-variables.json
  app/config/default.json
  app/config/test.json
  app/package-lock.json
  app/package.json
  app/src/components/errorToProblem.js
  app/src/components/index.js
  app/src/components/keycloakAdminService.js
  app/src/forms/common/constants.js
  app/src/forms/common/middleware/auth.js
  app/src/forms/form/constants.js
  app/src/forms/minesoperatorscreening/constants.js
  app/src/forms/minesoperatorscreening/index.js
  app/src/forms/teammanagement/controller.js
  app/src/forms/teammanagement/readme.md
  app/src/forms/teammanagement/router.js
  app/src/forms/teammanagement/service.js
  app/src/forms/testcase/index.js
  app/src/routes/v1.js
  app/tests/postman/Team Management (testcase).postman_collection.json
  openshift/README.md
  openshift/app.dc.yaml
Labels: enhancement

#69 Add generic unauthorized request functionality
  app/config/custom-environment-variables.json
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/components/common/RequestReceipt.vue
  app/frontend/src/services/commonFormService.js
  app/frontend/src/services/emailService.js
  app/frontend/src/services/index.js
  app/frontend/tests/unit/components/base/BaseSecure.spec.js
  app/frontend/tests/unit/services/commonFormService.spec.js
Labels: enhancement

#71 Request for Access notification
  app/src/db/migrations/20200529145912_008-settings-request-access.js
  app/src/forms/minesoperatorscreening/assets/access-requested-email.html
  app/src/forms/minesoperatorscreening/emailService.js
  app/src/forms/minesoperatorscreening/index.js
  app/src/forms/teammanagement/controller.js
  app/src/forms/teammanagement/router.js
Labels: enhancement
