Repository bcgov/common-forms-toolkit, pull requests merged in 2020-06, with the labels that each got.

#72 Add Team management page
  app/frontend/src/components/common/TeamTable.vue
  app/frontend/src/components/minesoperatorscreening/admin/AdminNavBar.vue
  app/frontend/src/router/comfort.js
  app/frontend/src/router/index.js
  app/frontend/src/router/minesOperatorScreening.js
  app/frontend/src/services/commonFormService.js
  app/frontend/src/store/modules/auth.js
  app/frontend/src/views/MinesOperatorScreening.vue
  app/frontend/src/views/minesoperatorscreening/Team.vue
  app/frontend/tests/unit/router/comfort.spec.js
  app/frontend/tests/unit/router/index.spec.js
  app/frontend/tests/unit/router/minesOperatorScreening.spec.js
  app/frontend/tests/unit/services/commonFormService.spec.js
  app/frontend/tests/unit/store/modules/auth.getters.spec.js
Labels: enhancement

#74 Team Management Assign Dropdown functionality
  app/frontend/src/components/common/TeamTable.vue
  app/frontend/src/services/commonFormService.js
  app/frontend/tests/unit/components/common/TeamTable.spec.js
  app/frontend/tests/unit/services/commonFormService.spec.js
  app/frontend/tests/unit/views/minesattestations/Team.spec.js
Labels: enhancement

#73 Refactor common data service
  app/src/db/migrations/20200602065740_009-minesoperatorscreening-common-model-changes.js
  app/src/forms/common/controller.js
  app/src/forms/common/dataService.js
  app/src/forms/common/events.js
  app/src/forms/common/models/base.js
  app/src/forms/common/models/index.js
  app/src/forms/common/router.js
  app/src/forms/form/models/base.js
  app/src/forms/form/models/index.js
  app/src/forms/minesoperatorscreening/controller.js
  app/src/forms/minesoperatorscreening/dataService.js
  app/src/forms/minesoperatorscreening/emailService.js
  app/src/forms/minesoperatorscreening/index.js
  app/src/forms/minesoperatorscreening/middleware/checkRole.js
  app/src/forms/minesoperatorscreening/middleware/index.js
  app/src/forms/minesoperatorscreening/middleware/searchParameters.js
  app/src/forms/minesoperatorscreening/models/base.js
  app/src/forms/minesoperatorscreening/models/index.js
  app/src/forms/minesoperatorscreening/models/searchParameters.js
  app/src/forms/minesoperatorscreening/models/submission.js
  app/src/forms/minesoperatorscreening/pdfService.js
  app/src/forms/minesoperatorscreening/router.js
  app/src/forms/minesoperatorscreening/routes.js
  app/src/forms/teammanagement/controller.js
  app/src/forms/teammanagement/events.js
  app/src/forms/teammanagement/router.js
  app/tests/postman/MinesOperatorScreening_v1.postman_collection.json
Labels: enhancement

#76 Fix submission table sorting on Firefox, Add legend to Team page
  app/frontend/src/components/common/TeamTable.vue
  app/frontend/src/components/minesoperatorscreening/admin/SubmissionsTable.vue
Labels: bug, enhancement

#77 Refresh token failure error handling.
  app/src/components/keycloakAdminService.js
Labels: bug

#75 Forestry Sector Operator Screening API/Model
  app/src/db/migrations/20200602090622_010-forestrysectoroperatorscreening-common.js
  app/src/db/migrations/20200602090631_010-forestrysectoroperatorscreening-form.js
  app/src/db/migrations/20200602090643_010-forestrysectoroperatorscreening-data.js
  app/src/forms/forestrysectoroperatorscreening/assets/access-requested-email.html
  app/src/forms/forestrysectoroperatorscreening/assets/confirmation-number-email.html
  app/src/forms/forestrysectoroperatorscreening/assets/generate-submission-pdf-001.html
  app/src/forms/forestrysectoroperatorscreening/assets/generate-submission-pdf-001.json
  app/src/forms/forestrysectoroperatorscreening/assets/status-assignment-email.html
  app/src/forms/forestrysectoroperatorscreening/constants.js
  app/src/forms/forestrysectoroperatorscreening/controller.js
  app/src/forms/forestrysectoroperatorscreening/dataService.js
  app/src/forms/forestrysectoroperatorscreening/emailService.js
  app/src/forms/forestrysectoroperatorscreening/index.js
  app/src/forms/forestrysectoroperatorscreening/middleware/index.js
  app/src/forms/forestrysectoroperatorscreening/middleware/searchParameters.js
  app/src/forms/forestrysectoroperatorscreening/models/base.js
  app/src/forms/forestrysectoroperatorscreening/models/index.js
  app/src/forms/forestrysectoroperatorscreening/models/searchParameters.js
  app/src/forms/forestrysectoroperatorscreening/models/submission.js
  app/src/forms/forestrysectoroperatorscreening/pdfService.js
  app/src/forms/forestrysectoroperatorscreening/router.js
  app/src/routes/v1.js
  app/tests/postman/ForestrySectorOperatorScreening_v1.postman_collection.json
Labels: enhancement

#87 Need to pass the operation type data as a context value.
  app/src/forms/agriseafoodopscreening/emailService.js
  app/src/forms/forestrysectoroperatorscreening/emailService.js
Labels: bug

#88 End to end AgriSeafoodOpService
  app/frontend/src/components/FormList.vue
  app/frontend/src/components/agriseafoodopscreening/admin/AdminReviewSubmission.vue
  app/frontend/src/components/agriseafoodopscreening/admin/SubmissionHeader.vue
  app/frontend/src/components/agriseafoodopscreening/admin/SubmissionsTable.vue
  app/frontend/src/components/agriseafoodopscreening/admin/inspection/InspectionPanel.vue
  app/frontend/src/components/agriseafoodopscreening/admin/inspection/NotesPanel.vue
  app/frontend/src/components/agriseafoodopscreening/admin/inspection/StatusTable.vue
  app/frontend/src/components/agriseafoodopscreening/admin/settings/SettingsPanel.vue
  app/frontend/src/services/agriSeafoodOpScreeningService.js
  app/frontend/src/store/modules/agriseafoodopscreening/agriSeafoodOpScreeningForm.js
  app/frontend/src/views/agriseafoodopscreening/Admin.vue
  app/frontend/src/views/agriseafoodopscreening/Dashboards.vue
  app/frontend/src/views/agriseafoodopscreening/Review.vue
  app/frontend/src/views/agriseafoodopscreening/Root.vue
  app/frontend/src/views/agriseafoodopscreening/Settings.vue
  app/frontend/src/views/agriseafoodopscreening/Submission.vue
  app/frontend/src/views/agriseafoodopscreening/Team.vue
Labels: bug, enhancement

#92 Carbone contacts looping fix
  app/src/forms/agriseafoodopscreening/assets/generate-submission-pdf-001.html
  app/src/forms/forestrysectoroperatorscreening/assets/generate-submission-pdf-001.html
  app/src/forms/minesoperatorscreening/assets/generate-submission-pdf-001.html
Labels: bug

#94 Bugfix Teams nav button showing when user is not admin
  app/frontend/src/components/common/AdminNavBar.vue
Labels: bug

#95 Use common submission header, include optionl type
  app/frontend/src/components/common/admin/SubmissionHeader.vue
  app/frontend/src/store/modules/agriseafoodopscreening/agriSeafoodOpScreeningForm.js
  app/frontend/src/store/modules/forestrysectoropscreening/forestrySectorOpScreeningForm.js
  app/frontend/src/views/agriseafoodopscreening/Submission.vue
  app/frontend/src/views/forestrysectoropscreening/Submission.vue
  app/frontend/src/views/minesoperatorscreening/Submission.vue
Labels: enhancement

#101 Frontend Service Layer Refactor
  app/frontend/src/components/agriseafoodopscreening/Step5.vue
  app/frontend/src/components/agriseafoodopscreening/admin/SubmissionsTable.vue
  app/frontend/src/components/agriseafoodopscreening/admin/inspection/InspectionPanel.vue
  app/frontend/src/components/agriseafoodopscreening/admin/inspection/NotesPanel.vue
  app/frontend/src/components/agriseafoodopscreening/admin/inspection/StatusTable.vue
  app/frontend/src/components/agriseafoodopscreening/admin/settings/SettingsPanel.vue
  app/frontend/src/components/common/RequestReceipt.vue
  app/frontend/src/components/common/admin/AdminNavBar.vue
  app/frontend/src/components/forestrysectoropscreening/Step5.vue
  app/frontend/src/components/forestrysectoropscreening/admin/SubmissionsTable.vue
  app/frontend/src/components/forestrysectoropscreening/admin/inspection/InspectionPanel.vue
  app/frontend/src/components/forestrysectoropscreening/admin/inspection/NotesPanel.vue
  app/frontend/src/components/forestrysectoropscreening/admin/inspection/StatusTable.vue
  app/frontend/src/components/forestrysectoropscreening/admin/settings/SettingsPanel.vue
  app/frontend/src/components/minesoperatorscreening/Step6.vue
  app/frontend/src/components/minesoperatorscreening/admin/SubmissionsTable.vue
  app/frontend/src/components/minesoperatorscreening/admin/inspection/InspectionPanel.vue
  app/frontend/src/components/minesoperatorscreening/admin/inspection/NotesPanel.vue
  app/frontend/src/components/minesoperatorscreening/admin/inspection/StatusTable.vue
  app/frontend/src/components/minesoperatorscreening/admin/settings/SettingsPanel.vue
  app/frontend/src/services/agriSeafoodOpScreeningService.js
  app/frontend/src/services/commonFormService.js
  app/frontend/src/services/forestrySectorOpSreeningService.js
  app/frontend/src/services/index.js
  app/frontend/src/services/minesOperatorScreeningService.js
  app/frontend/src/store/modules/agriseafoodopscreening/agriSeafoodOpScreeningForm.js
  app/frontend/src/store/modules/forestrysectoropscreening/forestrySectorOpScreeningForm.js
  app/frontend/src/store/modules/minesoperatorscreening/minesOperatorScreeningForm.js
  app/frontend/src/utils/constants.js
  app/frontend/src/views/AgriSeafoodOpScreening.vue
  app/frontend/src/views/ForestrySectorOpScreening.vue
  app/frontend/src/views/MinesOperatorScreening.vue
  app/frontend/src/views/agriseafoodopscreening/Dashboards.vue
  app/frontend/src/views/agriseafoodopscreening/Team.vue
  app/frontend/src/views/forestrysectoropscreening/Dashboards.vue
  app/frontend/src/views/forestrysectoropscreening/Team.vue
  app/frontend/src/views/minesoperatorscreening/Dashboards.vue
  app/frontend/src/views/minesoperatorscreening/Team.vue
  app/frontend/tests/unit/components/common/AdminNavBar.spec.js
  app/frontend/tests/unit/components/common/RequestReceipt.spec.js
  app/frontend/tests/unit/services/commonFormService.spec.js
  app/frontend/tests/unit/utils/constants.spec.js
Labels: enhancement

#107 Link and mailto
  app/frontend/src/components/agriseafoodopscreening/Landing.vue
Labels: bug

#108 Correct email
  app/frontend/src/components/agriseafoodopscreening/Landing.vue
Labels: bug

#106 Add data-test Attributes to Public Form pages
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/agriseafoodopscreening/Form.vue
  app/frontend/src/components/agriseafoodopscreening/Landing.vue
  app/frontend/src/components/agriseafoodopscreening/Step1.vue
  app/frontend/src/components/agriseafoodopscreening/Step2.vue
  app/frontend/src/components/agriseafoodopscreening/Step3.vue
  app/frontend/src/components/agriseafoodopscreening/Step4.vue
  app/frontend/src/components/agriseafoodopscreening/Step5.vue
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/src/components/base/BaseDialog.vue
  app/frontend/src/components/base/BaseHeaderSection.vue
  app/frontend/src/components/base/BaseHeaderSub.vue
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/components/bcgov/BCGovFooter.vue
  app/frontend/src/components/bcgov/BCGovHeader.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/components/common/Landing.vue
  app/frontend/src/components/common/RequestReceipt.vue
  app/frontend/src/components/common/admin/AdminNavBar.vue
  app/frontend/src/components/common/admin/SubmissionHeader.vue
  app/frontend/src/components/common/admin/SubmissionsTable.vue
  app/frontend/src/components/common/admin/inspection/InspectionPanel.vue
  app/frontend/src/components/common/admin/inspection/NotesPanel.vue
  app/frontend/src/components/common/admin/inspection/StatusTable.vue
  app/frontend/src/components/common/admin/settings/SettingsPanel.vue
  app/frontend/src/components/forestrysectoropscreening/Form.vue
  app/frontend/src/components/forestrysectoropscreening/Landing.vue
  app/frontend/src/components/forestrysectoropscreening/Step1.vue
  app/frontend/src/components/forestrysectoropscreening/Step2.vue
  app/frontend/src/components/forestrysectoropscreening/Step3.vue
  app/frontend/src/components/forestrysectoropscreening/Step4.vue
  app/frontend/src/components/forestrysectoropscreening/Step5.vue
  app/frontend/src/components/minesoperatorscreening/Form.vue
  app/frontend/src/components/minesoperatorscreening/Step1.vue
  app/frontend/src/components/minesoperatorscreening/Step2.vue
  app/frontend/src/components/minesoperatorscreening/Step3.vue
  app/frontend/src/components/minesoperatorscreening/Step4.vue
  app/frontend/src/components/minesoperatorscreening/Step5.vue
  app/frontend/src/components/minesoperatorscreening/Step6.vue
  app/frontend/src/views/minesoperatorscreening/Review.vue
Labels: enhancement

#110 Add seafood pdf
  app/frontend/src/components/agriseafoodopscreening/Landing.vue
Labels: enhancement

#109 Allow developers/testers to stand up their own database and Keycloak realm
  .gitignore
  app/.dockerignore
  app/bin/run-migrations.sh
  app/config/custom-environment-variables.json
  app/config/database.js
  app/config/default.json
  app/knexfile.js
  app/migration.Dockerfile
  local-infrastructure/.env
  local-infrastructure/README.md
  local-infrastructure/docker-compose.yml
  local-infrastructure/settings/keycloak-local-realm.json
  local-infrastructure/settings/keycloak-local-user.sh
Labels: enhancement

#111 Add the seafood contact info
  app/frontend/src/components/FormList.vue
  app/frontend/src/components/agriseafoodopscreening/Landing.vue
Labels: enhancement

#114 Back
  app/frontend/src/components/agriseafoodopscreening/Landing.vue
  app/frontend/src/components/agriseafoodopscreening/Step2.vue
  app/frontend/src/components/agriseafoodopscreening/Step3.vue
  app/frontend/src/components/agriseafoodopscreening/Step4.vue
  app/frontend/src/components/forestrysectoropscreening/Step3.vue
Labels: bug, enhancement

#113 Ensure all service calls in Vue use async/await try/catch instead of promise chains
  app/.eslintrc.js
  app/frontend/.eslintrc.js
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/components/common/RequestReceipt.vue
  app/frontend/src/components/common/admin/SubmissionsTable.vue
  app/frontend/src/components/common/admin/inspection/NotesPanel.vue
  app/frontend/src/components/common/admin/inspection/StatusTable.vue
  app/frontend/src/components/common/admin/settings/SettingsPanel.vue
  app/frontend/src/views/agriseafoodopscreening/Dashboards.vue
  app/frontend/src/views/forestrysectoropscreening/Dashboards.vue
  app/frontend/src/views/minesoperatorscreening/Dashboards.vue
  app/package-lock.json
  app/package.json
Labels: bug

#117 New questions for Agri
  app/frontend/src/components/agriseafoodopscreening/Step2.vue
  app/frontend/src/store/modules/agriseafoodopscreening/agriSeafoodOpScreeningForm.js
  app/src/db/migrations/20200616175436_014-agriseafoodopscreening-change-sleeping-fields.js
  app/src/forms/attestations/agriseafoodopscreening/assets/generate-submission-pdf-001.html
  app/src/forms/attestations/agriseafoodopscreening/models/form.js
  app/src/forms/attestations/minesoperatorscreening/models/form.js
  app/src/forms/attestations/models/submission.js
  app/tests/postman/AgriSeafoodOpScreening_v1.postman_collection.json
Labels: enhancement

#120 Add frontend unit test coverage for common form components
  app/frontend/src/components/agriseafoodopscreening/Step5.vue
  app/frontend/src/components/common/CityLookup.vue
  app/frontend/src/components/common/GeneratePdfButton.vue
  app/frontend/src/components/common/Landing.vue
  app/frontend/src/components/common/OrgBookSearch.vue
  app/frontend/src/components/common/PrintScreenButton.vue
  app/frontend/src/components/common/admin/SubmissionHeader.vue
  app/frontend/src/components/common/admin/SubmissionsTable.vue
  app/frontend/src/components/forestrysectoropscreening/Step5.vue
  app/frontend/src/components/minesoperatorscreening/Step6.vue
  app/frontend/src/views/agriseafoodopscreening/Review.vue
  app/frontend/src/views/agriseafoodopscreening/Submission.vue
  app/frontend/src/views/forestrysectoropscreening/Review.vue
  app/frontend/src/views/forestrysectoropscreening/Submission.vue
  app/frontend/src/views/minesoperatorscreening/Review.vue
  app/frontend/src/views/minesoperatorscreening/Submission.vue
  app/frontend/tests/unit/components/FormList.spec.js
  app/frontend/tests/unit/components/common/CityLookup.spec.js
  app/frontend/tests/unit/components/common/Dashboard.spec.js
  app/frontend/tests/unit/components/common/GeneratePdfButton.spec.js
  app/frontend/tests/unit/components/common/Landing.spec.js
  app/frontend/tests/unit/components/common/OrgBookSearch.spec.js
  app/frontend/tests/unit/components/common/PrintScreenButton.spec.js
  app/frontend/tests/unit/components/common/RequestReceipt.spec.js
  app/frontend/tests/unit/components/common/TeamTable.spec.js
  app/frontend/tests/unit/components/common/admin/AdminNavBar.spec.js
Labels: enhancement

#122 Forestry changes and some FE refactor
  app/frontend/src/components/agriseafoodopscreening/Step5.vue
  app/frontend/src/components/common/attestation/SubmissionConfirmation.vue
  app/frontend/src/components/forestrysectoropscreening/Landing.vue
  app/frontend/src/components/forestrysectoropscreening/Step1.vue
  app/frontend/src/components/forestrysectoropscreening/Step2.vue
  app/frontend/src/components/forestrysectoropscreening/Step3.vue
  app/frontend/src/components/forestrysectoropscreening/Step4.vue
  app/frontend/src/components/forestrysectoropscreening/Step5.vue
  app/frontend/src/components/minesoperatorscreening/Step6.vue
  app/frontend/src/utils/attestationFormOptions.js
  app/frontend/tests/unit/components/common/attestations/SubmissionConfirmation.spec.js
  app/frontend/tests/unit/utils/attestationFormOptions.spec.js
Labels: enhancement

#123 Small updates in docs files and structure
  app/frontend/src/components/minesoperatorscreening/Step2.vue
  tests/functional-tests/env.local
  tests/functional-tests/readme.md
  tests/integration/README.md
  tests/openshift/templates/README.md
  tests/performance/README.md
  tests/security/README.md
Labels: enhancement

#125 Commonize landing page
  app/frontend/src/components/agriseafoodopscreening/Form.vue
  app/frontend/src/components/agriseafoodopscreening/Landing.vue
  app/frontend/src/components/common/Landing.vue
  app/frontend/src/components/common/attestation/Landing.vue
  app/frontend/src/components/forestrysectoropscreening/Form.vue
  app/frontend/src/components/forestrysectoropscreening/Landing.vue
  app/frontend/src/utils/attestationFormOptions.js
  app/frontend/tests/unit/components/common/Landing.spec.js
  app/frontend/tests/unit/components/common/attestations/Landing.spec.js
Labels: enhancement

#124 Add unit test coverage to common admin components
  app/frontend/jest.config.js
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/components/common/RequestReceipt.vue
  app/frontend/src/components/common/admin/inspection/StatusTable.vue
  app/frontend/src/components/common/admin/settings/SettingItem.vue
  app/frontend/src/components/common/admin/settings/SettingsPanel.vue
  app/frontend/tests/unit/components/common/admin/SubmissionHeader.spec.js
  app/frontend/tests/unit/components/common/admin/SubmissionsTable.spec.js
  app/frontend/tests/unit/components/common/admin/inspection/InspectionPanel.spec.js
  app/frontend/tests/unit/components/common/admin/inspection/NotesPanel.spec.js
  app/frontend/tests/unit/components/common/admin/inspection/StatusTable.spec.js
  app/frontend/tests/unit/components/common/admin/settings/SettingItem.spec.js
  app/frontend/tests/unit/components/common/admin/settings/SettingsPanel.spec.js
  app/frontend/tests/unit/components/common/attestations/SubmissionConfirmation.spec.js
  app/frontend/tests/unit/router/agriSeafoodOpScreening.spec.js
  app/frontend/tests/unit/router/comfort.spec.js
  app/frontend/tests/unit/router/forestrySectorOpScreening.spec.js
  app/frontend/tests/unit/router/minesOperatorScreening.spec.js
  app/frontend/tests/unit/views/AgriSeafoodOpScreening.spec.js
  app/frontend/tests/unit/views/ForestrySectorOpScreening.spec.js
  app/frontend/tests/unit/views/MinesOperatorScreening.spec.js
  app/frontend/tests/unit/views/agriseafoodopscreening/Admin.spec.js
  app/frontend/tests/unit/views/agriseafoodopscreening/Dashboards.spec.js
  app/frontend/tests/unit/views/agriseafoodopscreening/Review.spec.js
  app/frontend/tests/unit/views/agriseafoodopscreening/Root.spec.js
  app/frontend/tests/unit/views/agriseafoodopscreening/Settings.spec.js
  app/frontend/tests/unit/views/agriseafoodopscreening/Submission.spec.js
  app/frontend/tests/unit/views/agriseafoodopscreening/Team.spec.js
  app/frontend/tests/unit/views/forestrysectoropscreening/Admin.spec.js
  app/frontend/tests/unit/views/forestrysectoropscreening/Dashboards.spec.js
  app/frontend/tests/unit/views/forestrysectoropscreening/Review.spec.js
  app/frontend/tests/unit/views/forestrysectoropscreening/Root.spec.js
  app/frontend/tests/unit/views/forestrysectoropscreening/Settings.spec.js
  app/frontend/tests/unit/views/forestrysectoropscreening/Submission.spec.js
  app/frontend/tests/unit/views/forestrysectoropscreening/Team.spec.js
  app/frontend/tests/unit/views/minesoperatorscreening/Admin.spec.js
  app/frontend/tests/unit/views/minesoperatorscreening/Dashboards.spec.js
  app/frontend/tests/unit/views/minesoperatorscreening/Review.spec.js
  app/frontend/tests/unit/views/minesoperatorscreening/Root.spec.js
  app/frontend/tests/unit/views/minesoperatorscreening/Settings.spec.js
  app/frontend/tests/unit/views/minesoperatorscreening/Submission.spec.js
  app/frontend/tests/unit/views/minesoperatorscreening/Team.spec.js
Labels: enhancement

#128 Bugfix buildconfig dying due to OOM Killed
  app/frontend/package.json
  openshift/app.bc.yaml
Labels: bug

#126 Feature/backend route tests
  app/jest.config.js
  app/src/forms/attestations/middleware/searchParameters.js
  app/src/forms/form/middleware/searchParameters.js
  app/src/forms/form/models/searchParameters.js
  app/tests/unit/attestationMocks.js
  app/tests/unit/attestations/controller.spec.js
  app/tests/unit/attestations/middleware/submissionSearch.spec.js
  app/tests/unit/commonMocks.js
  app/tests/unit/form/middleware/formSearch.spec.js
  app/tests/unit/routes/v1.spec.js
  app/tests/unit/teamMocks.js
Labels: enhancement

#127 BDDSTACK Consolidation and updated documentation and settings
  tests/functional-tests/build.gradle
  tests/functional-tests/env.local
  tests/functional-tests/gradle/versions.gradle
  tests/functional-tests/readme.md
  tests/functional-tests/src/test/groovy/pages/app/MinesOperatorPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/base/BaseAppPage.groovy
  tests/functional-tests/src/test/groovy/pages/modules/FooterModule.groovy
  tests/functional-tests/src/test/groovy/pages/modules/HeaderModule.groovy
  tests/functional-tests/src/test/groovy/pages/modules/ModalModule.groovy
  tests/functional-tests/src/test/groovy/specs/ComfortHomeSpec.groovy
  tests/functional-tests/src/test/groovy/specs/MinesOperatorSpec.groovy
  tests/functional-tests/src/test/resources/GebConfig.groovy
  tests/functional-tests/src/test/resources/GebSpockReportsConfig.groovy
  tests/functional-tests/src/test/resources/META-INF/services/com.athaydes.spockframework.report.IReportCreator.properties
  tests/functional-tests/src/test/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
  tests/openshift/configmap/configmap.yaml
  tests/openshift/pipelines/E2E-Test-JenkinsFile.groovy
  tests/openshift/pipelines/Performance-Test-JenkinsFile.groovy
  tests/openshift/pipelines/Security-Test-JenkinsFile.groovy
  tests/openshift/pipelines/Smoke-Test-JenkinsFile.groovy
  tests/openshift/templates/bddstack.bc.yaml
  tests/openshift/templates/e2e-test-pipeline.bc.yaml
Labels: documentation, enhancement

#129 Bugfix Registered Company lookup does not work when entering a non-alpha character
  app/frontend/src/components/common/CityLookup.vue
  app/frontend/src/components/common/OrgBookSearch.vue
Labels: bug

#130 Team management/Keycloak Guide
  README.md
  app/src/forms/testcase/index.js
  app/src/routes/v1.js
  app/tests/postman/Team Management (testcase).postman_collection.json
Labels: documentation

#132 Update general developer focused documentation
  COMPLIANCE.yaml
  README.md
  app/frontend/README.md
  app/src/forms/teammanagement/readme.md
  docs/developer-guide.md
  docs/overview.md
  docs/team-management.md
  local-infrastructure/README.md
Labels: documentation

#133 Feature/how to doc
  docs/how-to-add-form.md
  docs/sample/MyForm_v1.postman_collection.json
  docs/sample/db/migrations/20200626145729_myform-common.js
  docs/sample/db/migrations/20200626145736_myform-form.js
  docs/sample/db/migrations/20200626145742_myform-data.js
  docs/sample/forms/myform/constants.js
  docs/sample/forms/myform/controller.js
  docs/sample/forms/myform/dataService.js
  docs/sample/forms/myform/index.js
  docs/sample/forms/myform/models/form.js
  docs/sample/forms/myform/models/index.js
  docs/sample/forms/myform/router.js
  docs/team-management.md
Labels: documentation

#135 link in the how to guide for github pages.
  README.md
  docs/developer-guide.md
Labels: documentation

#134 Delete button for admin
  app/frontend/src/components/common/admin/SubmissionHeader.vue
  app/frontend/src/components/common/admin/inspection/DeleteButton.vue
  app/frontend/src/views/agriseafoodopscreening/Submission.vue
  app/frontend/src/views/forestrysectoropscreening/Submission.vue
  app/frontend/src/views/minesoperatorscreening/Submission.vue
  app/frontend/tests/unit/components/common/admin/inspection/DeleteButton.spec.js
Labels: enhancement

#136 Bugfix start button missing underline on hover
  app/frontend/src/components/agriseafoodopscreening/Form.vue
  app/frontend/src/components/forestrysectoropscreening/Form.vue
Labels: bug

#131 API spec - first draft
  app/frontend/src/components/FormList.vue
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
Labels: documentation
