Repository bcgov/common-forms-toolkit, pull requests merged in 2020-07, with the labels that each got.

#137 Update BCGovHeader to be more responsive
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/assets/images/bc_logo.svg
  app/frontend/src/assets/images/bc_logo_square.svg
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/bcgov/BCGovHeader.vue
  app/frontend/tests/unit/components/common/admin/inspection/DeleteButton.spec.js
  app/package-lock.json
  app/package.json
  openshift/README.md
Labels: enhancement

#139 Change v-content to v-main due to deprecation
  app/frontend/src/App.vue
  app/frontend/tests/unit/App.spec.js
Labels: bug

#140 Test Framework updates
  tests/functional-tests/build.gradle
  tests/functional-tests/env.local
  tests/functional-tests/src/main/groovy/listeners/BrowserStackReportingSpec.groovy
  tests/functional-tests/src/test/groovy/pages/app/HomePage.groovy
  tests/functional-tests/src/test/groovy/pages/app/MenuPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/MinesOperatorPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/base/BaseAppPage.groovy
  tests/functional-tests/src/test/groovy/pages/external/LoginPage.groovy
  tests/functional-tests/src/test/groovy/pages/modules/CheckboxModule.groovy
  tests/functional-tests/src/test/groovy/pages/modules/HeaderModule.groovy
  tests/functional-tests/src/test/groovy/specs/ComfortHomeSpec.bkp
  tests/functional-tests/src/test/groovy/specs/MinesOperatorSpec.groovy
  tests/functional-tests/src/test/groovy/specs/base/BaseSpec.groovy
  tests/functional-tests/src/test/groovy/specs/traits/Login.groovy
  tests/functional-tests/src/test/groovy/specs/traits/Users.groovy
  tests/functional-tests/src/test/groovy/specs/traits/Utils.groovy
  tests/functional-tests/src/test/resources/GebConfig.groovy
Labels: enhancement

#142 Updates to the tests and pipeline submissions POC for functional test
  tests/functional-tests/src/test/groovy/pages/app/AdminHomePage.groovy
  tests/functional-tests/src/test/groovy/pages/app/HomePage.groovy
  tests/functional-tests/src/test/groovy/pages/app/MenuPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/MinesAdminPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/MinesOperatorPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/SubmissionPage.groovy
  tests/functional-tests/src/test/groovy/specs/ComfortHomeSpec.groovy
  tests/functional-tests/src/test/groovy/specs/MinesOperatorSpec.groovy
  tests/functional-tests/src/test/groovy/specs/ReviewUserSpec.groovy
  tests/functional-tests/src/test/groovy/specs/traits/Login.groovy
  tests/functional-tests/src/test/groovy/specs/traits/Utils.groovy
  tests/openshift/configmap/configmap.yaml
  tests/openshift/pipelines/E2E-Test-JenkinsFile.groovy
  tests/openshift/templates/bddstack.bc.yaml
Labels: enhancement

#145 Dotting the Is and Striking the Ts
  tests/functional-tests/gradle/versions.gradle
  tests/functional-tests/src/main/groovy/listeners/BrowserStackAPI.groovy
  tests/functional-tests/src/main/groovy/listeners/BrowserStackGlobalExtension.groovy
  tests/functional-tests/src/main/groovy/listeners/BrowserStackReportingSpec.groovy
  tests/functional-tests/src/main/groovy/listeners/BrowserStackUpdateListener.groovy
  tests/functional-tests/src/main/groovy/listeners/SessionIdHolder.groovy
  tests/functional-tests/src/test/groovy/pages/app/AdminHomePage.groovy
  tests/functional-tests/src/test/groovy/pages/app/AgriSeafoodOperatorPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/HomePage.groovy
  tests/functional-tests/src/test/groovy/pages/app/MenuPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/MinesAdminPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/MinesOperatorPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/SubmissionPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/base/BaseAppPage.groovy
  tests/functional-tests/src/test/groovy/pages/app/modal/ConfirmDeleteModal.groovy
  tests/functional-tests/src/test/groovy/pages/app/modal/ConfirmSaveModal.groovy
  tests/functional-tests/src/test/groovy/pages/app/modal/ConfirmUpdateModal.groovy
  tests/functional-tests/src/test/groovy/pages/app/modal/SubmissionsConfirmSubmitModal.groovy
  tests/functional-tests/src/test/groovy/pages/external/ExternalLinkPage.groovy
  tests/functional-tests/src/test/groovy/pages/external/LoginAdminPage.groovy
  tests/functional-tests/src/test/groovy/pages/external/LoginPage.groovy
  tests/functional-tests/src/test/groovy/pages/modules/CheckboxModule.groovy
  tests/functional-tests/src/test/groovy/pages/modules/CommonLinkModule.groovy
  tests/functional-tests/src/test/groovy/pages/modules/FooterModule.groovy
  tests/functional-tests/src/test/groovy/pages/modules/HeaderModule.groovy
  tests/functional-tests/src/test/groovy/specs/ComfortHomeSpec.groovy
  tests/functional-tests/src/test/groovy/specs/MinesOperatorSpec.groovy
  tests/functional-tests/src/test/groovy/specs/NoAccessUserSpec.groovy
  tests/functional-tests/src/test/groovy/specs/ReviewUserSpec.groovy
  tests/functional-tests/src/test/groovy/specs/base/BaseSpec.groovy
  tests/functional-tests/src/test/groovy/specs/traits/Login.groovy
  tests/functional-tests/src/test/groovy/specs/traits/LoginAdmin.groovy
  tests/functional-tests/src/test/groovy/specs/traits/Users.groovy
  tests/functional-tests/src/test/groovy/specs/traits/Utils.groovy
  tests/functional-tests/src/test/resources/GebConfig.groovy
  tests/openshift/pipelines/E2E-Test-JenkinsFile.groovy
  tests/openshift/pipelines/Performance-Test-JenkinsFile.groovy
  tests/openshift/pipelines/Postman-Test-JenkinsFile.groovy
  tests/openshift/pipelines/Security-Test-JenkinsFile.groovy
  tests/openshift/pipelines/Smoke-Test-JenkinsFile.groovy
Labels: enhancement

#146 Apply various minor bugfixes
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/FormList.vue
  app/frontend/src/components/agriseafoodopscreening/Step1.vue
  app/frontend/src/components/common/TeamTable.vue
  app/frontend/src/components/forestrysectoropscreening/Step1.vue
  app/frontend/src/components/minesoperatorscreening/Step2.vue
  app/package-lock.json
  app/package.json
Labels: bug, dependencies
