Repository bcgov/common-forms-toolkit, pull requests merged in 2021-01, with the labels that each got.

#157 Add Github Actions Unit Testing and npm audit fixes
  .github/workflows/unit-tests.yaml
  app/frontend/package-lock.json
  app/frontend/package.json
  app/package-lock.json
  app/package.json
Labels: dependencies, enhancement

#158 Update Caddy Reverse Proxy to v2
  Jenkinsfile
  Jenkinsfile.cicd
  README.md
  app/frontend/jsconfig.json
  openshift/README.md
  openshift/caddy-reverse-proxy.dc.yaml
  openshift/commonPipeline.groovy
  vetur.config.js
Labels: documentation, enhancement

#159 Implement OCP4 Changes
  openshift/app.bc.yaml
  openshift/app.dc.yaml
  openshift/patroni-ephemeral.dc.yaml
  openshift/patroni.dc.yaml
  openshift/patroni.secret.yaml
Labels: enhancement

#160 Add tree planting option
  app/frontend/src/components/forestrysectoropscreening/Form.vue
  app/src/db/migrations/20200519164226_006-settings-table-data.js
  app/src/db/migrations/20200521134300_007-settings-receipt-to-submission.js
  app/src/db/migrations/20200529145912_008-settings-request-access.js
  app/src/db/migrations/20200602090643_010-forestrysectoroperatorscreening-data.js
  app/src/db/migrations/20200603145742_011-agriseafoodopscreening-data.js
  app/src/db/migrations/20210119090643_016-forestrysectoroperatorscreening-new-op-type.js
  app/tests/postman/AgriSeafoodOpScreening_v1.postman_collection.json
  app/tests/postman/ForestrySectorOperatorScreening_v1.postman_collection.json
  app/tests/postman/MinesOperatorScreening_v1.postman_collection.json
  local-infrastructure/README.md
  local-infrastructure/run.sh
  openshift/README.md
  tests/functional-tests/env.local
  tests/functional-tests/src/test/resources/GebConfig.groovy
  tests/openshift/configmap/configmap.yaml
Labels: documentation, enhancement
